Controllers/QuestionsLibController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Exam_Helper.ViewsModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Exam_Helper.Controllers
{
    public class QuestionsLibController : Controller
    {
        private readonly CommonDbContext _context;

        public QuestionsLibController(CommonDbContext context)
        {
            _context = context;
        }

        
        // GET: QuestionsLib
        public async Task<IActionResult> Index(string SearchString)
        {
            
            var ques = from que in _context.Question
                       select que; //await _context.Question.ToListAsync();
            if (!string.IsNullOrEmpty(SearchString))
                ques = ques.Where(x => x.Title.Contains(SearchString)
                                 || x.Proof.Contains(SearchString)
                                 || x.TagIds.Contains(SearchString)
                                 || x.Definition.Contains(SearchString));
            
            return View(await ques.ToListAsync());
        }

       

        // GET: QuestionsLib/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

           

            var question = await _context.Question
                .FirstOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // GET: QuestionsLib/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var tags = await _context.Tags.Select(x => new TagForQuestionCreatingModel()
            { Id = x.Id, Name = x.Title, IsSelected = false }).ToListAsync();
            
            return View(new ClassForQuestionCreatingModel() { question = new Question(), tags = tags});
        }

        // POST: QuestionsLib/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClassForQuestionCreatingModel obj)
        {
            if (ModelState.IsValid)
            {
                var StringTags = string.Join(";", obj.tags.Where(x=>x.IsSelected).Select(x=>x.Id));

                obj.question.CreationDate = DateTime.Now;
                obj.question.UpdateDate = DateTime.Now;
                obj.question.Author = "Admin";
                obj.question.TagIds = StringTags;
                _context.Add(obj.question);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(obj.question);
        }

        // GET: QuestionsLib/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Question.FindAsync(id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // POST: QuestionsLib/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  [Bind("Id,Definition,Title,Proof,Author,TagIds")] Question question)
        {
            if (id != question.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    var old = await _context.Question.AsNoTracking().FirstAsync(x => x.Id == id);
                    question.CreationDate = old.CreationDate;
                    question.UpdateDate = DateTime.Now;
                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(question.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(question);
        }

        // GET: QuestionsLib/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Question
                .FirstOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // POST: QuestionsLib/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var question = await _context.Question.FindAsync(id);
            _context.Question.Remove(question);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public RedirectToActionResult RedirectToTest(int id)
        {
            TempData["question_id"] = id;
            return RedirectToAction(nameof(Index), nameof(Tests));
        }

        private bool QuestionExists(int id)
        {
            return _context.Question.Any(e => e.Id == id);
        }
    }
}

Views/QuestionsLib/Create.cshtml
@model Exam_Helper.ViewsModel.ClassForQuestionCreatingModel;

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.question.Definition" class="control-label"></label>
                <input asp-for="@Model.question.Definition" class="form-control" />
                <span asp-validation-for="@Model.question.Definition" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.question.Title" class="control-label"></label>
                <input asp-for="@Model.question.Title" class="form-control" />
                <span asp-validation-for="@Model.question.Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.question.Proof" class="control-label"></label>
                <input asp-for="@Model.question.Proof" class="form-control" />
                <span asp-validation-for="@Model.question.Proof" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.tags" class="control-label"></label>
                <ul>
                    @for (int i = 0; i < Model.tags.Count; i++)
                    {
                        <li>
                            <input type="checkbox" asp-for="@Model.tags[i].IsSelected" />
                            <label asp-for="@Model.tags[i].IsSelected"> @Model.tags[i].Name</label>
                            <input type="hidden" asp-for="@Model.tags[i].Id" />
                            <input type="hidden" asp-for="@Model.tags[i].Name" />
                        </li>
                    }
                </ul>
                <span asp-validation-for="@Model.tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<button type="button" class="btn btn-light">
    <a asp-action="Index">Back to List</a>
</button>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/QuestionsLib/Delete.cshtml
@model Exam_Helper.Question

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Definition)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Definition)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Proof)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Proof)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TagIds)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TagIds)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <button type="button" class="btn btn-light">
            <a asp-action="Index">Back to List</a>
        </button>
    </form>
</div>

Views/QuestionsLib/Details.cshtml
@model Exam_Helper.Question

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Definition)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Definition)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Proof)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Proof)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TagIds)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TagIds)
        </dd>
    </dl>
</div>
<div>
    <button type="button" class="btn btn-light">
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    </button>
    <button type="button" class="btn btn-light">
        <a asp-action="Index">Back to List</a>
    </button>
</div>

Views/QuestionsLib/Edit.cshtml
@model Exam_Helper.Question

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Definition" class="control-label"></label>
                <input asp-for="Definition" class="form-control" />
                <span asp-validation-for="Definition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Proof" class="control-label"></label>
                <input asp-for="Proof" class="form-control" />
                <span asp-validation-for="Proof" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <!--hidden="true"-->
            <!--
                    <div class="form-group" >
                        <label asp-for="CreationDate" class="control-label"></label>
                        <input asp-for="CreationDate" class="form-control" />
                        <span asp-validation-for="CreationDate" class="text-danger"></span>
                    </div>
            <div class="form-group">
                <label asp-for="UpdateDate" class="control-label"></label>
                <input asp-for="UpdateDate" class="form-control" />
                <span asp-validation-for="UpdateDate" class="text-danger"></span>
            </div>
                -->
            <div class="form-group">
                <label asp-for="TagIds" class="control-label"></label>
                <input asp-for="TagIds" class="form-control" />
                <span asp-validation-for="TagIds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<button type="button" class="btn btn-light">
    <a asp-action="Index">Back to List</a>
</button>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/QuestionsLib/Index.cshtml
@model IEnumerable<Exam_Helper.Question>
@{
    ViewData["Title"] = "Library Page";
}

<main class="container" style="padding-top: 3vh;">
    <div class="container">

        <div class="justify-content text-center h1">
            <span>Библиотека</span>
        </div>

        <hr color="brown" />

        <div class="d-flex  bd-highlight pt-3 pb-3">
            <a asp-action="Create">
                <button type="button" class="btn btn-warning bd-highlight">Добавить Вопрос</button>
                </a>
                <div class="form-group pt-3 pb-3 bd-highlight ml-auto p-2"></div>
                <span class="mr-3"> Поиск вопроса: </span>
                <form asp-controller="QuestionsLib" asp-action="Index">
                    <input type="text" name="SearchString" class="form-control">
                </form>
        </div>
    </div>
    <!-- Массив вопросов, отображение потом настроим -->
    <table class="table">
        <thead>
            <tr>

                <th scope="col"> <span>@Html.DisplayNameFor(model => model.Definition)</span> </th>
                <th scope="col"> <span>@Html.DisplayNameFor(model => model.Title) </span></th>
                <th scope="col">tags</th>
                <th scope="col"> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td> <span>@Html.DisplayFor(modelItem => item.Definition) </span></td>
                    <td> <span>@Html.DisplayFor(modelItem => item.Title) </span></td>
                    <td> <span>@Html.DisplayFor(modelItem => item.TagIds) </span></td>
                    <td>
                        <div class=" d-flex justify-content-center dropdown">
                            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Actions
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                <a class="dropdown-item" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                <a class="dropdown-item" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                <a class="dropdown-item" asp-action="RedirectToTest" asp-route-id="@item.Id">Tests</a>
                            </div>

                        </div>
                    </td>
                </tr>

            }
        </tbody>
    </table>
</main>